spring:
  datasource:
    username: root
    password: passw0rd
    url: jdbc:mysql://localhost:3306/mybooks?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
